-- Create parcels table
CREATE TABLE IF NOT EXISTS public.parcels (
    ulpin TEXT PRIMARY KEY,
    state TEXT NOT NULL,
    district TEXT NOT NULL,
    parcel_data JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create audit_logs table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp BIGINT NOT NULL,
    user_role TEXT NOT NULL,
    ulpin TEXT NOT NULL,
    action TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.parcels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Allow anonymous operations for parcels (since auth is not set up)
CREATE POLICY "Allow anonymous read parcels"
ON public.parcels
FOR SELECT
TO anon
USING (true);

CREATE POLICY "Allow anonymous insert parcels"
ON public.parcels
FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "Allow anonymous update parcels"
ON public.parcels
FOR UPDATE
TO anon
USING (true);

-- Allow anonymous operations for audit_logs
CREATE POLICY "Allow anonymous read audit_logs"
ON public.audit_logs
FOR SELECT
TO anon
USING (true);

CREATE POLICY "Allow anonymous insert audit_logs"
ON public.audit_logs
FOR INSERT
TO anon
WITH CHECK (true);
